linters:
  enable:
  - exhaustive
  - goconst
  - goerr113
  - gofmt
  - gofumpt
  - goimports
  - golint
  - goprintffuncname
  - gosec
  - interfacer
  - misspell
  - whitespace
linters-settings:
  goimports:
    local-prefixes: github.com/klmitch/nelson
